# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=64)),
                ('article_body', models.TextField(max_length=256)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('article_praise', models.IntegerField()),
            ],
        ),
    ]
