# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_user',
            field=models.CharField(default='', max_length=64),
        ),
    ]
